### ISSUE TITLE
Dapr AWS SSO not picking up AWS_CREDENTIALS_PROFILES_FILE to read credentials

### ISSUE THREAD

**Issue by subash89** [dapr/components-contrib#1145]
Steps to recreate:
1. In your ~/.aws/config provide a AWS_PROFILE which will do external credential source.(https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html)
In my case, it dumps credentials to a custom path directed via AWS_CREDENTIALS_PROFILES_FILE ~/.aws/myorg-credentials

2. Now when start daprd and app with dynamod state component, and when app tries to read a value from dynamodb state, it fails with following. It dos not honor read credentials from AWS_CREDENTIALS_PROFILES_FILE. If I manually copy creds to ~/.aws/credentials it works fine.

io.dapr.exceptions.DaprException: INTERNAL: fail to get key1 from state store mydynamodb: NoCredentialProviders: no valid providers in chain. Deprecated.
                For verbose messaging see aws.Config.CredentialsChainVerboseErrors
                at io.dapr.exceptions.DaprException.propagate(DaprException.java:168)
                at io.dapr.client.DaprClientGrpc$2.onError(DaprClientGrpc.java:727)
                at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
                at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)

**Comment by CodeMonkeyLeet** [comment]
I'm not particularly familiar with the AWS authentication provider in Dapr, but just looking at [credential handling](https://github.com/dapr/components-contrib/blob/45f577e137a6188be88606c1f9c9be34ff6adc04/authentication/aws/aws.go#L17) suggests that it only works with static credentials provided through the component metadata fields (`AccessKey`, `SecretKey` and `SessionToken` and token properties like in dynamodb).

I'm not sure if this would work differently for the underlying aws-go-sdk, but it seems like there would need to be an epic similar to https://github.com/dapr/components-contrib/issues/1103 for Azure; AWS components already do at least all seem to go through the common auth component, but expanding the support to other AWS auth configurations is also probably something that could use contributor help with.
