### ISSUE TITLE
Error when calling Azure Blob Storage output binding for blobs list

### ISSUE THREAD

**Issue by francotiveron** [dapr/components-contrib#1832]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.7

this is the binding component yaml

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: studybinding
spec:
  type: bindings.azure.blobstorage
  version: v1
  initTimeout: 1m
  metadata:
  - name: accountName
    value: "hfconfigsa"
  - name: accountKey
    value: "<hidden>"
  - name: containerName
    value: "studyresult"
```
this is the F# .NET code run to get the lost of blobs
```
let request = 
    let r = BindingRequest("studybinding", "list")
    r.Data <- (
            {|
            maxResults = 10
            prefix = "file"
            marker = "2!108!MDAwMDM1IWZpbGUtMDgtMDctMjAyMS0wOS0zOC01NS03NzgtMjEudHh0ITAwMDAyOCE5OTk5LTEyLTMxVDIzOjU5OjU5Ljk5OTk5OTlaIQ--"
            ``include`` = {|
                snapshots = false
                metadata = true
                uncommittedBlobs = false
                copy = false
                deleted = false |} |}
        |> toUtf8Json
        ).AsMemory()
    r

let! response = daprClient.InvokeBindingAsync(request) 
```

Below the exception raised

```
Exception has occurred: CLR/Dapr.DaprException
Exception thrown: 'Dapr.DaprException' in System.Private.CoreLib.dll: 'Binding operation failed: the Dapr endpoint indicated a failure. See InnerException for details.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Grpc.Core.RpcException : Status(StatusCode="Internal", Detail="error when invoke output binding studybinding: error listing blobs: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, C:/Users/runneradmin/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154
HTTP request failed

Get "https://.blob.core.windows.net/?comp=list&include=metadata&marker=2%21108%21MDAwMDM1IWZpbGUtMDgtMDctMjAyMS0wOS0zOC01NS03NzgtMjEudHh0ITAwMDAyOCE5OTk5LTEyLTMxVDIzOjU5OjU5Ljk5OTk5OTlaIQ--&maxresults=10&prefix=file&restype=container&timeout=61": dial tcp: lookup .blob.core.windows.net: no such host
")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapr.Client.DaprClientGrpc.<MakeInvokeBindingRequestAsync>d__21.MoveNext()

```

Note. the url indicated seems incorrect (https://**???**.blob.core.windows.net/?...)

**Comment by ItalyPaleAle** [comment]
#1837 will fix this by allowing all options
