### ISSUE TITLE
Mongodb state-store not working

### ISSUE THREAD

**Issue by bencz** [dapr/components-contrib#1991]
When creating/configuring the state-store as mongodb, writing and initializing works correctly, but when trying to read some information from the state-store, a serialization error occurs.

Another point, when comparing the creation of the actors' reminders partitions in other databases, such as PgSQL, in mongo db, every time the application is restarted, more N partitions of the reminders are created

## Expected Behavior

Return state-store information

## Actual Behavior

Exception when trying to deserialize information

```
[18:06:10 ERR] An unhandled exception has occurred while executing the request.
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.actorDetailsId | LineNumber: 0 | BytePositionInLine: 21.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Dapr.Actors.Runtime.DaprStateProvider.TryLoadStateAsync[T](String actorType, String actorId, String stateName, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorStateManager.TryGetStateAsync[T](String stateName, CancellationToken cancellationToken)
   at DaprMongoDbBug.API.Actors.BugStateStoreActor.GetActorDetails() in /src/src/DaprMongoDbBug.API/Actors/BugStateStoreActorSample.cs:line 36
   at DaprMongoDbBug.API.Actors.BugStateStoreActor.ExecuteSampleReminder1() in /src/src/DaprMongoDbBug.API/Actors/BugStateStoreActorSample.cs:line 50
   at DaprMongoDbBug.API.Actors.BugStateStoreActor.ReceiveReminderAsync(String reminderName, Byte[] state, TimeSpan dueTime, TimeSpan period) in /src/src/DaprMongoDbBug.API/Actors/BugStateStoreActorSample.cs:line 71
   at Dapr.Actors.Runtime.ActorManager.<>c__DisplayClass24_0.<<FireReminderAsync>g__RequestFunc|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorManager.FireReminderAsync(ActorId actorId, String reminderName, Stream requestBodyStream, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Builder.ActorsEndpointRouteBuilderExtensions.<>c__DisplayClass4_0.<<MapReminderEndpoint>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Steps to Reproduce the Problem

Change the state-store host/server on "dapr/components/daprmongodbbug-statestore.yaml"
I've attached an example ASP.Net core project, just run docker-compose (note there is a docker compose override)

Execute the sample project running the docker-compose,
Navigate to: http://127.0.0.1:5200/swagger/index.html
Execute the endpoint: createActor sending some paramters on model ( the field id is the actor id )
After this, try to read the actor details on the "GET" endpoint

[DaprMongoDbBug.zip](https://github.com/dapr/components-contrib/files/9396651/DaprMongoDbBug.zip)

**Comment by berndverst** [comment]
Which Dapr version are you running? And which Dapr SDK and version are you using? Could you also share the Mongo DB version? Is this in Docker?

**Comment by bencz** [comment]
Hi
I did the test with Dapr 1.8.3 and 1.8.4
I'm using the dotnet-sdk version 1.8.0
The mongodb, I have used the managed Atlas MongoDB ( https://www.mongodb.com/ )
I did the test with the free version of Atlas MongoDB and with the payed version too, I just got the same problem

**Comment by bencz** [comment]
@berndverst 
I just did some debug, and I found a very interesting problem...

The actor state model is:

```
public class ActorDetails
{
    public int ActorDetailsId { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
    public string City { get; set; }
}
```

Ok, so, ActorDetailsId is a integer... I just added a "Console.WriteLine" on this method, https://github.com/dapr/dotnet-sdk/blob/0c9d6a45c8d3792a92d7141056c390bea098d02b/src/Dapr.Actors/Runtime/DaprStateProvider.cs#L46 , to print the stringResult variable, this is what I got:

![image](https://user-images.githubusercontent.com/1174448/187858905-77e0d59a-5f1d-4e79-9c2a-7832086efb40.png)

So, all the integers values Dapr is returning as float/double/decimal

**Comment by bencz** [comment]
Also, I just did a test, and I hard coded the right json on stringResult variable, I, this problem has been "solved"
So, it's looks like a serialization problem from dapr to client or state-store do dapr... I don't know...

**Comment by berndverst** [comment]
> Also, I just did a test, and I hard coded the right json on stringResult variable, I, this problem has been "solved"
> 
> So, it's looks like a serialization problem from dapr to client or state-store do dapr... I don't know...

I'm pretty sure that we cannot preserve integer type and always return it as float/double given JSON serialization. That part seems expected to me. I'll have to dig into that again.

**Comment by bencz** [comment]
with a custom converter, it is possible to resolve, in parts, this problem...
for example, like this:

```csharp
public class CustomInt32Converter : JsonConverter<int>
{
    public override int Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        switch (reader.TokenType)
        {
            case JsonTokenType.Number:
            {
                return reader.TryGetInt32(out var int32Value) 
                    ? int32Value
                    : Convert.ToInt32(reader.GetDecimal());
            }
            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    public override void Write(Utf8JsonWriter writer, int value, JsonSerializerOptions options) =>
        writer.WriteNumberValue(value);
}

public class ActorDetails
{
    [JsonConverter(typeof(CustomInt32Converter))]
    public int ActorDetailsId { get; set; }
    public string Name { get; set; }
    
    [JsonConverter(typeof(CustomInt32Converter))]
    public int Age { get; set; }
    public string City { get; set; }
}
```

It could be a problem, if we share the same "ActorDetails" class with other projects and needs to make a serialization too

**Comment by berndverst** [comment]
@bencz the .NET SDK maintainer (@halspang ) and I for components-contrib got together to talk about this problem (Hal is also an expert on our actor runtime).

We recommend that you either use a String type to represent the Actor ID or use a Decimal type, unless you want to use a custom serializer.

**Comment by halspang** [comment]
> Another point is, why with PgSql or Redis, this problem doesn't occur and with mongoDb it does?

The different underlying stores encode data in their own ways. Mongo, if it thinks it cannot convert a number to be an `int32` it'll store it as a `double`. I'm not sure why it thinks those numbers cannot be stored as an int, but I believe that to be what's happening. 

A test, that may be easier, is to try storing your `int`s as `long`s. According to the mongo docs, `long`s don't seem to get converted to `double`. 

https://www.mongodb.com/docs/mongodb-shell/reference/data-types/

**Comment by berndverst** [comment]
The problem is that Go unmarshals integers in JSON as float64, and then the Mongo Driver BSON library will naturally insert this as float / double.

Here is a simple test case that shows that Go treats numbers in JSON as floats:
https://go.dev/play/p/BsEfqT9CQgh

**Comment by berndverst** [comment]
So the issue is here:
https://github.com/dapr/dapr/blob/683a436ff1367e4ff2d27da2d79069c04ec2c46d/pkg/http/api.go#L1268

This only impacts HTTP calls. Currently all Actor APIs are HTTP only. Additionally, to be impacted you would need to use a state store that has native support for JSON documents - most of our state stores do not.

Impacted: MongoDB, RethinkDB, not sure about others.

@yaron2 @artursouza I think this issue should be transferred to Dapr/Dapr.

The particular line above would need to do the following:
After unmarshalling examine whether any nested `float64` with the `interface{}` actually represents an integer and then cast that to the appropriate integer type.

**Comment by berndverst** [comment]
@halspang using longs can't mitigate this given the problem is the JSON deserialization.

**Comment by artursouza** [comment]
> So the issue is here: https://github.com/dapr/dapr/blob/683a436ff1367e4ff2d27da2d79069c04ec2c46d/pkg/http/api.go#L1268
> 
> This only impacts HTTP calls. Currently all Actor APIs are HTTP only. Additionally, to be impacted you would need to use a state store that has native support for JSON documents - most of our state stores do not.
> 
> Impacted: MongoDB, RethinkDB, not sure about others.
> 
> @yaron2 @artursouza I think this issue should be transferred to Dapr/Dapr.
> 
> The particular line above would need to do the following: After unmarshalling examine whether any nested `float64` with the `interface{}` actually represents an integer and then cast that to the appropriate integer type.

We have gRPC API for actors too but only the Java SDK (I think) uses that.

**Comment by artursouza** [comment]
Moving this to dapr/dapr as this issue is impacting documentdb state stores broadly.
