### ISSUE TITLE
Java API for Pluggable components can't run on MacOS

### ISSUE THREAD

**Issue by tmacam** [dapr/components-contrib#2117]
## Describe the feature

While trying to run the pluggable components Java SDK on MacOS users receive the following error:

```
INFO: Taking unix socket domain path from env. var. DAPR_COMPONENT_SOCKET_PATH
Sep 22, 2022 4:35:54 PM org.example.StateStoreComponentServer main
INFO: Starting a StateStoreComponentServer...
Sep 22, 2022 4:35:54 PM org.example.StateStoreComponentServer buildUnixSocketServer
INFO: Configuring server to listen to unix socket domain on file /tmp/sharedUDS/javaMemstore.socket
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
    at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:81)
    at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:54)
    at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:186)
    at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:37)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:114)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:101)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:78)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:54)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:47)
    at org.example.StateStoreComponentServer.buildUnixSocketServer(StateStoreComponentServer.java:86)
    at org.example.StateStoreComponentServer.main(StateStoreComponentServer.java:63)
Caused by: java.lang.ExceptionInInitializerError
    at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40)
    ... 14 more
Caused by: java.lang.IllegalStateException: Only supported on Linux
    at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:317)
    at io.netty.channel.epoll.Native.<clinit>(Native.java:85)
    ... 15 more

```

This might be a problem with Netty support for UDS but regardless it needs to be addressed. FWIW, this might be the wrong repo for this issue.

**Comment by artursouza** [comment]
Which Java version?

**Comment by berndverst** [comment]
This should not be filed under contrib repo

**Comment by tmacam** [comment]
Moved to https://github.com/dapr-sandbox/components-java-sdk/issues/10
