### ISSUE TITLE
Sql Server state component error:  Dapr.Actors.ActorMethodInvocationException

### ISSUE THREAD

**Issue by CarlosLanderas** [dapr/components-contrib#229]
## Issue Description

I am trying to replace the redis store by azure sql server. The target table is created successfuly but whenever I try to create a proxy actor I get this error when trying to execute a method
Unhandled exception. Dapr.Actors.ActorMethodInvocationException: Remote Actor Method Exception

```
---> Dapr.Actors.DaprException: not found
at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken) at Dapr.Actors.DaprHttpInteractor.SendAsync(Func1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
at Dapr.Actors.DaprHttpInteractor.GetStateAsync(String actorType, String actorId, String keyName, CancellationToken cancellationToken)
at Dapr.Actors.Runtime.DaprStateProvider.ContainsStateAsync(String actorType, String actorId, String stateName, CancellationToken cancellationToken)

```

## Actual Behavior

Receiving a Remoted Actor Method not found
If I swap sqlstate.yaml with redis state.yaml everything works fine again

**LOGS:**

```
== DAPR == time="2020-02-21T12:14:57+01:00" level=info msg="starting Dapr Runtime -- version 0.4.0 -- commit v0.3.0-rc.0-73-ga1e270f-dirty"

== DAPR == time="2020-02-21T12:14:57+01:00" level=info msg="log level set to: info"

== DAPR == time="2020-02-21T12:14:57+01:00" level=info msg="standalone mode configured"

== DAPR == time="2020-02-21T12:14:57+01:00" level=info msg="dapr id: lande_actor"

== DAPR == time="2020-02-21T12:14:57+01:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation"

== DAPR == time="2020-02-21T12:14:57+01:00" level=info msg="loaded component statestore (state.sqlserver)"

== DAPR == time="2020-02-21T12:14:57+01:00" level=info msg="loaded component servicebus (pubsub.azure.servicebus)"

== DAPR == time="2020-02-21T12:14:57+01:00" level=info msg="application protocol: http. waiting on port 5000"

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Now listening on: http://localhost:5000

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Application started. Press Ctrl+C to shut down.

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Hosting environment: Development

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Content root path: C:\source\labs\dapr\dotnet\MyActorService

== DAPR == time="2020-02-21T12:15:00+01:00" level=info msg="application discovered on port 5000"

== DAPR == time="2020-02-21T12:15:00+01:00" level=info msg="application configuration loaded"

== APP == Listing subscription topics

== DAPR == time="2020-02-21T12:15:01+01:00" level=info msg="App is subscribed to the following topics: [topic1]"

== DAPR == time="2020-02-21T12:15:02+01:00" level=info msg="Initialized service discovery to standalone"

== DAPR == time="2020-02-21T12:15:02+01:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"

== DAPR == time="2020-02-21T12:15:02+01:00" level=info msg="actors: starting connection attempt to placement service at localhost:6050"

== DAPR == time="2020-02-21T12:15:02+01:00" level=info msg="http server is running on port 3500"

== DAPR == time="2020-02-21T12:15:02+01:00" level=info msg="gRPC server is running on port 27443"

== DAPR == time="2020-02-21T12:15:02+01:00" level=info msg="local service entry announced"

== DAPR == time="2020-02-21T12:15:02+01:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 4775.6745ms"
```

Sql state store definition file:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
name: statestore
spec:
type: state.sqlserver
metadata:
- name: connectionString
  value: server=server.database.windows.net;user id=dwlab;password=pass!;port=1433;database=db1;
- name: tableName
  value: dapr
- name: actorStateStore
  value: "true"
```

**Comment by yaron2** [comment]
The error coming from Dapr is probably different than the one surfaced by the dotnet SDK here.

Can you add the `--log-level debug` flag to `dapr run` and see if there's any suspicious messages showing?

**Comment by CarlosLanderas** [comment]
Hello @yaron2. First of all, congrats for your amazing work. I'm very hyped with Dapr!

Executing using:

`dapr run --port 3500 --app-id lande_actor --app-port 5000 --log-level debug dotnet run`

Shows errors:

```
== DAPR == time="2020-02-21T12:19:48+01:00" level=debug msg="error establishing client to placement service: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp [::1]:6050: connectex: No connection could be made because the target machine actively refused it.\""

== DAPR == time="2020-02-21T12:19:51+01:00" level=debug msg="error establishing client to placement service: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp [::1]:6050: connectex: No connection could be made because the target machine actively refused it.\""

== DAPR == time="2020-02-21T12:19:53+01:00" level=debug msg="error establishing client to placement service: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp [::1]:6050: connectex: No connection could be made because the target machine actively refused it.\""
```

**Comment by CarlosLanderas** [comment]
Thanks @yaron2, first of all congrats for your great work.

I can see some reminder errors:

 dapr run --port 3500 --app-id lande_actor --app-port 5000 --log-level debug dotnet run
Starting Dapr with id lande_actor. HTTP Port: 3500. gRPC Port: 27772
You're up and running! Both Dapr and your app logs will appear here.

```
== DAPR == time="2020-02-21T12:23:23+01:00" level=info msg="starting Dapr Runtime -- version 0.4.0 -- commit v0.3.0-rc.0-73-ga1e270f-dirty"

== DAPR == time="2020-02-21T12:23:23+01:00" level=info msg="log level set to: debug"

== DAPR == time="2020-02-21T12:23:23+01:00" level=info msg="standalone mode configured"

== DAPR == time="2020-02-21T12:23:23+01:00" level=info msg="dapr id: lande_actor"

== DAPR == time="2020-02-21T12:23:23+01:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation"

== DAPR == time="2020-02-21T12:23:23+01:00" level=info msg="loaded component statestore (state.sqlserver)"

== DAPR == time="2020-02-21T12:23:23+01:00" level=info msg="loaded component servicebus (pubsub.azure.servicebus)"

== DAPR == time="2020-02-21T12:23:23+01:00" level=info msg="application protocol: http. waiting on port 5000"

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Now listening on: http://localhost:5000

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Application started. Press Ctrl+C to shut down.

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Hosting environment: Development

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Content root path: C:\source\labs\dapr\dotnet\MyActorService

== DAPR == time="2020-02-21T12:23:24+01:00" level=info msg="application discovered on port 5000"

== DAPR == time="2020-02-21T12:23:24+01:00" level=info msg="application configuration loaded"

== APP == Listing subscription topics

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="App is subscribed to the following topics: [topic1]"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="Initialized service discovery to standalone"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: starting connection attempt to placement service at localhost:6050"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="http server is running on port 3500"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="gRPC server is running on port 27772"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="local service entry announced"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 2451.4822ms"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: established connection to placement service at localhost:6050"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: placement order received: lock"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: placement order received: update"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: placement tables updated"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: placement order received: unlock"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: placement order received: lock"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: placement order received: update"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: placement tables updated"

== DAPR == time="2020-02-21T12:23:25+01:00" level=info msg="actors: placement order received: unlock"

== DAPR == time="2020-02-21T12:23:26+01:00" level=debug msg="error getting reminders for actor type MyActor: not found"

== DAPR == time="2020-02-21T12:23:27+01:00" level=debug msg="error getting reminders for actor type MyActor: not found"
```

**Comment by yaron2** [comment]
Thanks, that's always great to hear!

Lets try and get the actual error from Dapr by invoking the actor over HTTP instead of going through the SDK.

Issue the next call to Dapr via HTTP:

Method: `POST`
Url: `http://localhost:3500/v1.0/actors/MyActor/123/<MethodNameOnYourActor>`
Body: <JSON-PAYLOAD>

**Comment by CarlosLanderas** [comment]
Sorry, forgot to mention I already tried that:

POST: http://127.0.0.1:3500/v1.0/actors/MyActor/1/method/GetDataAsync
```json
{
    "errorCode": "ERR_ACTOR_INVOKE_METHOD",
    "message": "error from actor service: Dapr.Actors.DaprException: not found\r\n   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)\r\n   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)\r\n   at Dapr.Actors.DaprHttpInteractor.GetStateAsync(String actorType, String actorId, String keyName, CancellationToken cancellationToken)\r\n   at Dapr.Actors.Runtime.DaprStateProvider.TryLoadStateAsync[T](String actorType, String actorId, String stateName, CancellationToken cancellationToken)\r\n   at Dapr.Actors.Runtime.ActorStateManager.TryGetStateAsync[T](String stateName, CancellationToken cancellationToken)\r\n   at Dapr.Actors.Runtime.ActorStateManager.GetStateAsync[T](String stateName, CancellationToken cancellationToken)\r\n   at CallSite.Target(Closure , CallSite , Object )\r\n   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)\r\n   at Dapr.Actors.Runtime.ActorManager.<>c__DisplayClass15_0.<<DispatchWithoutRemotingAsync>g__RequestFunc|0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)\r\n   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)\r\n   at Dapr.Actors.Runtime.ActorManager.DispatchWithoutRemotingAsync(ActorId actorId, String actorMethodName, Stream requestBodyStream, Stream responseBodyStream, CancellationToken cancellationToken)\r\n   at Dapr.Actors.AspNetCore.RouterBuilderExtensions.<>c.<<AddActorMethodRoute>b__3_0>d.MoveNext()"
}
```

**Comment by yaron2** [comment]
Great. Try this next:

Method: 'GET'
Url: 'http://localhost:3500/v1.0/actors/MyActor/123/state/<a-state-key-that-you-have>`

**Comment by yaron2** [comment]
In that case, the key should be the one used in the `GetDataAsync` method on the actor.

**Comment by CarlosLanderas** [comment]
It will be familiar to you as it's the key from the tutorial:

```csharp
        public async Task<string> SetDataAsync(MyData data)
        {
            await StateManager.SetStateAsync<MyData>("my_data", data);
            return "Success";
        }

        public Task<MyData> GetDataAsync()
        {
            // Gets state from the state store.
            return this.StateManager.GetStateAsync<MyData>("my_data");
        }
```

GET http://127.0.0.1:3500/v1.0/actors/MyActor/1/state/my_data

Response:

```json
{
    "errorCode": "ERR_ACTOR_STATE_GET",
    "message": "not found"
}

**Comment by yaron2** [comment]
Good job!

We now know it's coming from here:
https://github.com/dapr/components-contrib/blob/5b75f4d0fbc6cee6b8ef2576abd203eb826e8032/state/sqlserver/sqlserver.go#L440

**Comment by yaron2** [comment]
Are you able to save state?

**Comment by CarlosLanderas** [comment]
SetDataAsync is the method triggering the exception in the first place:

```csharp
Starting execution!
Creating proxy
Sending data
Unhandled exception. Dapr.Actors.ActorMethodInvocationException: Remote Actor Method Exception
 ---> Dapr.Actors.DaprException: not found
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
```

**Comment by yaron2** [comment]
Ok so we really need to try and save the data with HTTP, because if the data fails to get written than its normal for the not found error to return

**Comment by yaron2** [comment]
Method: `POST`
Url: `http://localhost:3500/v1.0/actors/MyActor/1/state/my_data`
Body: `"{\"name\":\"test\"}"`

**Comment by CarlosLanderas** [comment]
POST http://localhost:3500/v1.0/actors/MyActor/1/state/my_data

Status Code: 201 created

GET http://localhost:3500/v1.0/actors/MyActor/1/state/my_data

Status Code: 200

Data is succesfully stored in Sql Server:

![image](https://user-images.githubusercontent.com/16475649/75032646-52962800-54a9-11ea-928e-ec02d002d4fe.png)

**Comment by yaron2** [comment]
And if you use the C# SDK now to Get the state?

**Comment by CarlosLanderas** [comment]
Working!. So it looks like when there is not state initialized the sql server state crashes using the SDK

**Comment by yaron2** [comment]
Can you try to use the C# SDK to invoke an actor with a new ID?

**Comment by yaron2** [comment]
It'll probably fail.. just want to make sure.

**Comment by CarlosLanderas** [comment]
Exactly. Crash again. GetStateAsync is failing

```csharp
Unhandled exception. Dapr.Actors.ActorMethodInvocationException: Remote Actor Method Exception
 ---> Dapr.Actors.DaprException: not found
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.GetStateAsync(String actorType, String actorId, String keyName, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.DaprStateProvider.ContainsStateAsync(String actorType, String actorId, String stateName, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorStateManager.SetStateAsync[T](String stateName, T value, CancellationToken cancellationToken)
   at MyActorService.MyActor.SetDataAsync(MyData data) in C:\source\labs\dapr\dotnet\MyActorService\MyActor.cs:line 31
   at Dapr.Actors.Builder.ActorMethodDispatcherBase.<>c__DisplayClass14_0`1.<ContinueWithResult>b__0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Dapr.Actors.Runtime.ActorManager.<>c__DisplayClass14_0.<<DispatchWithRemotingAsync>g__RequestFunc|0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.InvokeAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task)
   at MyActorClient.Program.Main(String[] args) in C:\source\labs\dapr\dotnet\MyActorClient\Program.cs:line 25
   at MyActorClient.Program.<Main>(String[] args)

```

**Comment by yaron2** [comment]
Ok I see why this is happening. The SQL Server implementation treats a non-existing key as an error, but it shouldn't. It should return an empty response.

We'll fix that sooner rather than later.
Thanks a lot for helping debug this.

**Comment by CarlosLanderas** [comment]
You are welcome @yaron2 . Thanks for your support
