### ISSUE TITLE
Zookeeper

### ISSUE THREAD

**Issue by pamav** [dapr/components-contrib#2999]
Hi,
Dapr StateManagement -> components Zookeeper

After call 
 await daprClient.SaveStateAsync("zookeeper",0);
I got exception

```
Dapr Exception:
Unhandled exception. Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==  ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="failed saving state in state store zookeeper: zk: invalid path")
== APP ==    at Dapr.Client.DaprClientGrpc.MakeSaveStateCallAsync[TValue](String storeName, String key, TValue value, String etag, StateOptions stateOptions, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==    --- End of inner exception stack trace ---
== APP ==    at Dapr.Client.DaprClientGrpc.MakeSaveStateCallAsync[TValue](String storeName, String key, TValue value, String etag, StateOptions stateOptions, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
```

zookeeper log:
```
[NIOWorkerThread-1:o.a.z.s.ZooKeeperServer@1422] - Connection request from old client /172.17.0.1:42248; will be dropped if server is in r-o mode
INFO  [SyncThread:0:o.a.z.s.p.FileTxnLog@285] - Creating new log file: log.1
INFO  [NIOWorkerThread-3:o.a.z.s.NIOServerCnxn@337] - Unable to read additional data from client, it probably closed the socket: address = /172.17.0.1:42248, session = 0x10000
```

Zookeeper version :3.8.1
Dapr version: 1.11.1
Docker version:24.0.2

**Comment by pamav** [comment]
Component Yaml file it is same like in DAPR doc.

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zookeeper
spec:
  type: state.zookeeper
  version: v1
  metadata:
  - name: servers
    value: localhost:2181
  - name: sessionTimeout
    value: "15s"

**Comment by berndverst** [comment]
@pamav did you run zookeeper in docker? if so, do you have the image you used?

**Comment by pamav** [comment]
Yes I run zookeeper in docker.
Image is latest. I currently using zookeeper v:3.8.1

**Comment by pamav** [comment]
Any result?
